version: "3.0"

services:
  php82:
    build:
      context: . # Use the current directory or specify the relative path to the Dockerfile
      dockerfile: Dockerfile # You can omit this line if the Dockerfile is named `Dockerfile` and is in the context directory
#    depends_on:
#    - redis
    image: laravel/build
    volumes:
      - C:\Projects\PARKWAY\YurWallet.API:/var/www/html
      - ./configs:/cfgs
      - ./configs:/configs
      - ./logs:/var/log
    env_file: .env
    hostname: php82
    container_name: php82
    restart: always
    networks:
      - my_app_network

  php_queue:
    image: laravel/build
    volumes:
      - C:\Projects\PARKWAY\YurWallet.API:/var/www/html
      - ./configs:/cfgs
      - ./configs:/configs
      - ./logs:/var/log
    depends_on:
      - php82
    env_file: .env
    command: /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
    container_name: php_queue
    restart: always
    networks:
      - my_app_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    restart: always
    volumes:
      - ./nginx/conf.d/default.d:/etc/nginx/conf.d/default.conf
      - ./nginx/keys:/keys
      - C:\Projects\PARKWAY\YurWallet.API:/var/www/html
    ports:
      - 9001:80
    networks:
      - my_app_network

#  redis:
#    image: redis:latest

networks:
  my_app_network:
    driver: bridge
